import {searchYouTube} from '../connectors/youtube.mjs';
import {searchGitHub} from '../connectors/github.mjs';
import {searchWeb} from '../connectors/web.mjs';
import {searchOfficialDocs} from '../connectors/official-docs.mjs';
import {searchImages,searchAudio,searchTikTok,searchFacebook} from '../connectors/media.mjs';
import {chooseSources,normalizeSources,VALID_SOURCES} from './source-policy.mjs';
import {rankAndDeduplicate} from './rank.mjs';
import {verifySources} from './verify.mjs';
import {synthesize} from './llm.mjs';
const cache=new Map();
function validate(body){const question=String(body?.question||'').trim();if(!question||question.length>2000)throw new Error('Invalid question');const language=['ar','en','auto'].includes(body?.language)?body.language:'auto';const mode=['all','text','visual','audio'].includes(body?.mode)?body.mode:'all';const requested=normalizeSources(body?.sources);if(Array.isArray(body?.sources)&&requested.length===0&&body.sources.length)throw new Error(`Invalid sources. Allowed: ${VALID_SOURCES.join(', ')}`);return{question,language,mode,requested}}
export async function runKnowledgeQuery(body={}){const {question,language,mode,requested}=validate(body);const selected=chooseSources(question,requested);const cacheKey=JSON.stringify({question,language,mode,selected});const ttl=Number(process.env.KNOWLEDGE_CACHE_SECONDS||300)*1000;const cached=cache.get(cacheKey);if(cached&&Date.now()-cached.at<ttl)return{...cached.data,cache:'hit'};const timeoutMs=Number(process.env.KNOWLEDGE_CONNECTOR_TIMEOUT_MS||8000);const tasks=selected.map(source=>{if(source==='web')return searchWeb({query:question,maxResults:8});if(source==='youtube')return searchYouTube({query:question,language,maxResults:6,timeoutMs});if(source==='github')return searchGitHub({query:question,maxResults:6,timeoutMs});if(source==='official_docs')return searchOfficialDocs({query:question,maxResults:8});if(source==='images')return searchImages({query:question,maxResults:6});if(source==='audio')return searchAudio({query:question,maxResults:6});if(source==='tiktok')return searchTikTok({query:question});if(source==='facebook')return searchFacebook({query:question});return Promise.resolve({connector:source,status:'unsupported',results:[],reason:'No connector'});});const settled=await Promise.allSettled(tasks);const connectorResults=settled.map((x,i)=>x.status==='fulfilled'?x.value:{connector:selected[i],status:'error',results:[],reason:x.reason?.message||'connector failure'});const discovered=rankAndDeduplicate(connectorResults);const verified=await verifySources(discovered,{limit:Number(process.env.KNOWLEDGE_VERIFY_SOURCES||12),timeoutMs});const ranked=rankAndDeduplicate([{results:verified}]).slice(0,Number(process.env.KNOWLEDGE_MAX_SOURCES||12));const usable=ranked.filter(s=>s.verification?.status==='verified');
  const allDisabled=connectorResults.length>0&&connectorResults.every(x=>['disabled','unsupported'].includes(x.status));
  const noAiKeys=!process.env.OPENROUTER_API_KEY&&!process.env.GROQ_API_KEY;
  const ai=usable.length?await synthesize({question,language,mode,sources:usable}):noAiKeys||allDisabled?await synthesize({question,language,mode,sources:[]}):{status:'blocked',data:{answer:'No verified sources were retrieved. The Knowledge Engine will not generate a source-backed answer until at least one real source is successfully retrieved and verified.',title:'Knowledge verification required',steps:[],teachingPoints:[],actions:[],caveats:['Real source retrieval or source verification failed; the answer was blocked to prevent unsupported claims.'],citations:[]},provider:null,model:null,responseId:null};const citations=(ai.data?.citations||[]).map(id=>usable.find(s=>(s.id||s.url)===id)).filter(Boolean).map(s=>({id:s.id||s.url,title:s.title,url:s.url,verified:s.verification?.status==='verified',official:!!s.verification?.official,source:s.source}));const data={ok:true,question,language,mode,selectedSources:selected,connectorStatus:connectorResults.map(x=>({connector:x.connector,status:x.status,reason:x.reason||null,resultCount:(x.results||[]).length})),verification:{checked:verified.length,verified:verified.filter(x=>x.verification?.status==='verified').length,official:verified.filter(x=>x.verification?.official).length},answer:ai.data?.answer||'',title:ai.data?.title||'AI HUB Knowledge Answer',steps:ai.data?.steps||[],teachingPoints:ai.data?.teachingPoints||[],actions:ai.data?.actions||[],caveats:ai.data?.caveats||[],citations,sources:ranked,aiStatus:ai.status,aiProvider:ai.provider||null,aiModel:ai.model||null,aiResponseId:ai.responseId||null,engineVersion:'2.1.1-free'};cache.set(cacheKey,{at:Date.now(),data});return{...data,cache:'miss'}}
